import React, { useRef, forwardRef } from "react";
import {
  Radar,
  RadarChart,
  PolarGrid,
  PolarAngleAxis,
  PolarRadiusAxis,
  ResponsiveContainer,
} from "recharts";

const PDFReport = forwardRef((props, ref) => {
  const { studentName, chartData, careers, avoid, traits } = props;

  return (
    <div ref={ref} className="bg-white p-8 max-w-4xl mx-auto">
      {/* Header */}
      <div className="text-center mb-8 border-b pb-4">
        <h1 className="text-3xl font-bold text-blue-700 mb-2">
          Career Assessment Report
        </h1>
        <p className="text-lg text-gray-600">
          Student: <span className="font-semibold">{studentName}</span>
        </p>
        <p className="text-sm text-gray-500">
          Generated on {new Date().toLocaleDateString()}
        </p>
      </div>

      {/* Personality Profile Chart */}
      <div className="mb-8">
        <h2 className="text-2xl font-bold text-blue-700 mb-4">
          Personality Profile
        </h2>
        <div className="bg-gray-50 p-4 rounded-lg">
          <ResponsiveContainer width="100%" height={300}>
            <RadarChart data={chartData}>
              <PolarGrid />
              <PolarAngleAxis dataKey="trait" />
              <PolarRadiusAxis angle={30} domain={[0, 5]} />
              <Radar
                name="Score"
                dataKey="score"
                stroke="#2563eb"
                fill="#3b82f6"
                fillOpacity={0.6}
              />
            </RadarChart>
          </ResponsiveContainer>
        </div>
        <div className="mt-4">
          <h3 className="font-semibold text-gray-700 mb-2">Trait Scores:</h3>
          <div className="grid grid-cols-2 gap-2 text-sm">
            {Object.entries(traits).map(([trait, score]) => (
              <div key={trait} className="flex justify-between">
                <span className="capitalize">{trait}:</span>
                <span className="font-medium">{score.toFixed(1)}/5.0</span>
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* Recommended Careers */}
      <div className="mb-8">
        <h2 className="text-2xl font-bold text-green-700 mb-4">
          Recommended Careers
        </h2>
        <div className="space-y-4">
          {careers.map((career, index) => (
            <div key={index} className="bg-green-50 p-4 rounded-lg border-l-4 border-green-500">
              <h3 className="text-lg font-semibold text-green-800 mb-2">
                {career.title}
              </h3>
              <p className="text-gray-700">{career.reason}</p>
            </div>
          ))}
        </div>
      </div>

      {/* Careers to Avoid */}
      <div className="mb-8">
        <h2 className="text-2xl font-bold text-red-700 mb-4">
          Careers to Avoid
        </h2>
        <div className="bg-red-50 p-4 rounded-lg border-l-4 border-red-500">
          <ul className="space-y-2 text-gray-700">
            {avoid.map((item, index) => (
              <li key={index} className="flex items-start">
                <span className="text-red-500 mr-2">•</span>
                {item}
              </li>
            ))}
          </ul>
        </div>
      </div>

      {/* Footer */}
      <div className="text-center mt-8 pt-4 border-t text-sm text-gray-500">
        <p>This report was generated by AI Career Counselling System</p>
        <p>For best results, consider consulting with a career counselor</p>
      </div>
    </div>
  );
});

PDFReport.displayName = "PDFReport";
export default PDFReport;
